name: BuildAndTest

on: [ push ]

jobs:
  build:
    name: BuildAndTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11', '1.12.x' ]
    steps:
      - uses: actions/checkout@master
      - name: Build Glog
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build *.go